# Generated by Django 5.0.1 on 2024-02-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
