# Generated by Django 5.0.1 on 2024-02-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0002_alter_category_table_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='_categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table='_products',
        ),
    ]
