# Generated by Django 5.0.1 on 2024-02-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCustomer', '0005_alter_customer_table_alter_ordercontainer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='_customers',
        ),
        migrations.AlterModelTable(
            name='ordercontainer',
            table='_order_containers',
        ),
    ]
