# Generated by Django 5.0.1 on 2024-02-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCustomer', '0007_rename_customer_id_ordercontainer_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '_testing',
            },
        ),
    ]
